### ISSUE TITLE
Duplicated React-dom production in the bundle

### ISSUE THREAD

**Issue by satanworker** [frontend-collective/frontend-collective-react-dnd-scrollzone#47]
I think the problem is react and react-dom should be in peer and dev dependencies and not in dependences in package.json
But I might be wrong. 
*The setup* 
I'm using simple create-react-app and reat-sortable-tree which has front-end-collective-react-dnd-scrollzone as dependency. But in the final bundle React-dom is bundled twice. 
<img width="1499" alt="Screenshot 2020-04-25 at 14 25 39" src="https://user-images.githubusercontent.com/11026240/80277572-03ff4700-8701-11ea-9e84-532f2500bef9.png">
I've checked package.json of all packages and all the react version satisfies react latest version, so I think the problem is only with peerDependencies 

Let me know if I can help and thank you!

**Comment by FBNitro** [comment]
FYI: I raised a similar issue on react-sortable-tree, since it's depending on this: https://github.com/frontend-collective/react-sortable-tree/issues/753

I figure it would get more exposure over there.

**Comment by MM-at-work** [comment]
It looks like the fix is already in package.json as react and react-dom are already listed as peerDependencies.
However, the latest 1.0.2 release in the npm registry does not have the same package.json changes.

@wuweiweiwu perhaps just a republish will resolve the issue?

**Comment by satanworker** [comment]
I think the problem is solved!
